# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: circleci/node:6-stretch
    steps:
      - checkout
      - run: 
          command: npm install -q
      - run:
          name: snyk auth
          command: snyk auth $SNYK_TOKEN
      - snyk/scan:
        - fail-on-issues: false                                     # don't fail even if issues detected (not recommended!)
        - monitor-on-build: true     
workflows: null