# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          token-variable: SNYK_TOKEN
workflows: null